### ISSUE TITLE
Play Live Stream not working

### ISSUE THREAD

**Issue by sarawutl** [ant-media/LiveVideoBroadcaster#1] opened 2017-08-12 09:05 UTC
please help

**Comment by sarawutl** [comment] 2017-08-12 12:28
08-12 19:25:14.955 6255-6255/io.antmedia.android.livevideopublisher I/uri :: /tan/XikaoxhEnYQp51Ycz6Zf
08-12 19:25:14.986 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger: state [0.03, true, B]
08-12 19:25:14.988 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger: sourceInfo [periodCount=1, windowCount=1
08-12 19:25:14.988 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger:   period [?]
08-12 19:25:14.988 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger:   window [?, false, false]
08-12 19:25:14.988 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger: ]
08-12 19:25:15.052 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger: loading [true]
08-12 19:25:25.215 6255-6255/io.antmedia.android.livevideopublisher E/EventLogger: internalError [10.26, loadError]
                                                                                   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:713)
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)
08-12 19:25:25.222 6255-7026/io.antmedia.android.livevideopublisher E/ExoPlayerImplInternal: Source error.
                                                                                             com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:713)
                                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                 at java.lang.Thread.run(Thread.java:818)
08-12 19:25:25.226 6255-6255/io.antmedia.android.livevideopublisher E/EventLogger: playerFailed [10.27]
                                                                                   com.google.android.exoplayer2.ExoPlaybackException
                                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                    Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:713)
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)
08-12 19:25:25.229 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger: loading [false]
08-12 19:25:25.229 6255-6255/io.antmedia.android.livevideopublisher D/EventLogger: state [10.28, true, I]

**Comment by mekya** [comment] 2017-08-12 12:41
Hi @sarawutl 

Have you added " live=1" to the end of the url when trying to play?
For instance assume that your live stream is "test_stream", then you should enter
"test_stream live=1" to the app to play the live stream via rtmp.

Could you please confirm that you already do this and it is still not working?

Regards,
A. Oguz

**Comment by sarawutl** [comment] 2017-08-12 12:45
Hi @mekya 

Not working

this error : 
08-12 19:44:51.325 31343-31343/io.antmedia.android.livevideopublisher I/uri :: /tan/test live=1
08-12 19:44:51.371 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger: state [0.05, true, B]
08-12 19:44:51.372 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger: sourceInfo [periodCount=1, windowCount=1
08-12 19:44:51.373 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger:   period [?]
08-12 19:44:51.377 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger:   window [?, false, false]
08-12 19:44:51.377 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger: ]
08-12 19:44:51.456 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger: loading [true]
08-12 19:44:59.471 1258-1308/? D/hwcomposer: hw_composer sent 103 syncs in 60s
08-12 19:45:01.566 31343-31343/io.antmedia.android.livevideopublisher E/EventLogger: internalError [10.24, loadError]
                                                                                     com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:713)
                                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                                         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                         at java.lang.Thread.run(Thread.java:818)
08-12 19:45:01.576 31343-32562/io.antmedia.android.livevideopublisher E/ExoPlayerImplInternal: Source error.
                                                                                               com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:713)
                                                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
08-12 19:45:01.579 31343-31343/io.antmedia.android.livevideopublisher E/EventLogger: playerFailed [10.26]
                                                                                     com.google.android.exoplayer2.ExoPlaybackException
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                         at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                      Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:713)
                                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                                         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                         at java.lang.Thread.run(Thread.java:818)
08-12 19:45:01.589 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger: loading [false]
08-12 19:45:01.589 31343-31343/io.antmedia.android.livevideopublisher D/EventLogger: state [10.27, true, I]

**Comment by mekya** [comment] 2017-08-14 10:12
Do you write ip address correctly and are you sure that there is live stream with that name in the server?

Regards,

**Comment by sarawutl** [comment] 2017-08-14 10:14
Ip address correct, I'm test on https://www.wowza.com/testplayers it working

**Comment by mekya** [comment] 2017-08-14 12:58
May I connect to server and test somehow? Maybe using teamviewer?

**Comment by sarawutl** [comment] 2017-08-14 16:03
rtmp://103.77.116.229:1935/tan/xFqpcnwJKMmJM3sTVDOH

**Comment by mekya** [comment] 2017-08-15 11:22
I can't event play this url via VLC or ffplay. 

It seems there is an another issue in the system.

**Comment by sarawutl** [comment] 2017-08-15 13:52
how to fix, help me please

**Comment by mekya** [comment] 2017-08-15 19:19
Are you sure that someone is continuously broadcasting live to this url?

rtmp://103.77.116.229:1935/tan/xFqpcnwJKMmJM3sTVDOH

**Comment by sarawutl** [comment] 2017-08-15 19:21
now this url rtmp://103.77.116.229:1935/tan/wBE9d5wLRiHxasxZ1XR3

**Comment by mekya** [comment] 2017-08-15 19:27
OK. I can play it with ffplay. Right now I am trying with the android app. Please keep broadcasting

**Comment by mekya** [comment] 2017-08-15 19:28
btw, do you use Ant Media Server as a rtmp server?

**Comment by mekya** [comment] 2017-08-15 19:46
Ok. You can finish broadcasting.  I find out the problem. 

The problem is your media server and exoplayer ScriptTagPayloadReader does not fit to each other. I have come across this issue a couple of times. 

Anyway, there is a fix for this issue, you should change the lines between https://github.com/ant-media/LiveVideoBroadcaster/blob/master/app/src/main/java/io/antmedia/android/liveVideoPlayer/flvExtractor/ScriptTagPayloadReader.java#L83 and https://github.com/ant-media/LiveVideoBroadcaster/blob/master/app/src/main/java/io/antmedia/android/liveVideoPlayer/flvExtractor/ScriptTagPayloadReader.java#L94

with the code below. Then it is likely to play. Let me know if it still does not work for you. 


    if (type != AMF_TYPE_ECMA_ARRAY) {
      // Should never happen.
      //   throw new ParserException();
    }
    else {
      // Set the duration to the value contained in the metadata, if present.
      Map<String, Object> metadata = readAmfEcmaArray(data);
      if (metadata.containsKey(KEY_DURATION)) {
        double durationSeconds = (double) metadata.get(KEY_DURATION);
        if (durationSeconds > 0.0) {
          durationUs = (long) (durationSeconds * C.MICROS_PER_SECOND);
        }
      }
    }

**Comment by sarawutl** [comment] 2017-08-19 06:14
ScriptTagPayloadReader.java in io.antmedia.android.liveVideoPlayer.flvExtractor never use

but Player call com.google.android.exoplayer2.extractor.flv.ScriptTagPayloadReader

**Comment by mekya** [comment] 2017-08-19 06:28
Player natively calls  com.google.android.exoplayer2.extractor.flv.ScriptTagPayloadReader

On the other side, live video player in this repo calls [DefaultExtractorsFactoryForFLV](https://github.com/ant-media/LiveVideoBroadcaster/blob/master/app/src/main/java/io/antmedia/android/liveVideoPlayer/DefaultExtractorsFactoryForFLV.java) that uses the [ flv extractor and script tag payload reader](https://github.com/ant-media/LiveVideoBroadcaster/tree/master/app/src/main/java/io/antmedia/android/liveVideoPlayer/flvExtractor) in this repo

**Comment by sarawutl** [comment] 2017-08-19 06:41
working, thank you

**Comment by mekya** [comment] 2017-08-19 06:54
You're welcome,

Closing the issue, if you have a question please let me know.

**Closed by mekya** 2017-08-19 06:54 UTC
